---
name: Deploy to production

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Run tests with Jest
        run: yarn test --ci

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build React app
        run: yarn build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
